# Generated by Django 4.1.7 on 2023-03-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='user',
            new_name='employee_name',
        ),
    ]
