# Generated by Django 4.1.7 on 2023-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_name',
            field=models.CharField(max_length=60),
        ),
    ]
