# Generated by Django 4.1.7 on 2023-03-01 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_employeeproject_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='applications/resume')),
                ('expected_salary', models.SmallIntegerField(choices=[('50k', '50k'), ('70k', '70k'), ('80k', '80k'), ('100k', '100k'), ('150k', '150k'), ('200k', '200k'), ('250k', '250k')])),
                ('summary', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
