# Generated by Django 4.1.7 on 2023-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.CharField(choices=[('50k', '50k'), ('70k', '70k'), ('80k', '80k'), ('100k', '100k'), ('150k', '150k'), ('200k', '200k'), ('250k', '250k')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='applications/resume'),
        ),
    ]
