# Generated by Django 4.1.7 on 2023-03-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_description', models.TextField(blank=True, max_length=150, null=True)),
                ('required_skills', models.CharField(choices=[('Py', 'Python'), ('React', 'React'), ('DJ', 'Django'), ('FLASK', 'Flask'), ('HTML', 'Html'), ('CSS', 'CSS')], max_length=50)),
                ('number_of_positions', models.PositiveIntegerField()),
                ('job_location', models.CharField(max_length=30)),
                ('minimum_qualification_required', models.CharField(choices=[('matric', 'Matric'), ('inter', 'Intermediate'), ('BS', 'BSCS'), ('Master-in-Math', 'Master in Math'), ('S-Engineering', 'Sofware Engineering')], max_length=20)),
                ('required_experience', models.CharField(max_length=30)),
                ('minimum_salary', models.PositiveIntegerField()),
                ('maximum_salary', models.PositiveIntegerField()),
                ('salary_visibility', models.BooleanField(default=True)),
                ('gender_prefrences', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=20)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiters.recruiter')),
            ],
        ),
    ]
