# Generated by Django 4.1.7 on 2023-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_timing',
            field=models.CharField(choices=[('Full_Time', 'Full Time'), ('Part_Time', 'Part Time'), ('Contract', 'Contract')], default='Full Time', max_length=30),
        ),
    ]
