# Generated by Django 4.1.7 on 2023-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
    ]
