# Generated by Django 4.1.7 on 2023-03-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_alter_jobpost_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiters.recruiter'),
        ),
    ]
