# Generated by Django 4.1.7 on 2023-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_alter_jobpost_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
