# Generated by Django 4.1.7 on 2023-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_jobpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
