# Generated by Django 4.1.7 on 2023-03-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0010_jobpost_company_jobpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiters.company'),
        ),
    ]
