# Generated by Django 4.1.7 on 2023-03-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0011_alter_jobpost_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
    ]
