# Generated by Django 4.1.7 on 2023-03-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0012_remove_jobpost_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company',
        ),
    ]
