# Generated by Django 4.1.7 on 2023-03-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0013_remove_recruiter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='recruiters.company'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recruiters.company'),
        ),
    ]
